#!/usr/bin/env bash
#install and setup haproxy on an ubuntu machine

#Update package list and install haproxy
apt-get update
apt-get -y install haproxy

#enable haproxy init script

#configure the haproxy to forward requests to my two servers using the round-robin algorithm
echo "


#my config
frontend web-frontend
        mode tcp
	bind *:80
	default_backend web-backend

backend web-backend
        balance roundrobin
	server 124330-web-01 54.146.88.176:80 check
	server 124330-web-02 52.91.146.155:80 check
" >> /etc/haproxy/haproxy.cfg
#restart haproxy
service haproxy restart
